// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXy6tSjdtu5ukcSDHo04mng3RtyKANTFk',
    appId: '1:370380317647:web:7941890cfdcd4ab3d828ba',
    messagingSenderId: '370380317647',
    projectId: 'sumquiz-f56f3',
    authDomain: 'sumquiz-f56f3.firebaseapp.com',
    storageBucket: 'sumquiz-f56f3.firebasestorage.app',
    measurementId: 'G-SFP6KGVPLF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjFvU2akvhB5JjbhoMAE6SxWtjgmWBft4',
    appId: '1:370380317647:android:0d5c6aa1e3be9e56d828ba',
    messagingSenderId: '370380317647',
    projectId: 'sumquiz-f56f3',
    storageBucket: 'sumquiz-f56f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOkIaXsWFxYLMbWlI5f7v4qgkHtDxLOIU',
    appId: '1:370380317647:ios:1c4311ac30d82191d828ba',
    messagingSenderId: '370380317647',
    projectId: 'sumquiz-f56f3',
    storageBucket: 'sumquiz-f56f3.firebasestorage.app',
    iosClientId:
        '370380317647-35hovctgu028i1ahvmd8t7fpcp3mcj1t.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOkIaXsWFxYLMbWlI5f7v4qgkHtDxLOIU',
    appId: '1:370380317647:ios:1c4311ac30d82191d828ba',
    messagingSenderId: '370380317647',
    projectId: 'sumquiz-f56f3',
    storageBucket: 'sumquiz-f56f3.firebasestorage.app',
    iosClientId:
        '370380317647-35hovctgu028i1ahvmd8t7fpcp3mcj1t.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXy6tSjdtu5ukcSDHo04mng3RtyKANTFk',
    appId: '1:370380317647:web:7941890cfdcd4ab3d828ba',
    messagingSenderId: '370380317647',
    projectId: 'sumquiz-f56f3',
    authDomain: 'sumquiz-f56f3.firebaseapp.com',
    storageBucket: 'sumquiz-f56f3.firebasestorage.app',
    measurementId: 'G-SFP6KGVPLF',
  );
}
